---
title: "Tidy data"
author: "Sara Pedro"
date: "February 13, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE}
library(dplyr)
library(tidyr)

# to call stats filter - stats::filter()
# the code above does not let warnings and messages show on the markdown version
```


# Reformat catch data

* Remove "All" and "notes" columns
* Create "Species" column
    - move from wide to long
* General QA

## Data citation

[Mike Byerly. Alaska commercial salmon catches by management region (1886- 1997). Gulf of Alaska Data Portal. df35b.304.2.] (https://knb.ecoinformatics.org/view/df35b.304.2)



```{r}

# Read data from a url - from the an online data bank

catch_original <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method = "libcurl"), stringsAsFactors = FALSE)

head(catch_original)

```

Remove the "All" and "notesRegCode" columns

ctrl+shit+m : pipe operator shortcut %>% 

```{r}

catch_long <- catch_original %>%
  select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum) %>% # or select(-All, -notesRegCode)
  gather(key = species, value = catch, -Region, -Year) # Move from wide to long; Region and Year are not going to be gathered into the species and catch columns


head(catch_long)

```


Opposite code of gather is spread - gets data set back from long to wide

```{r}
catch_wide <- catch_long %>% 
  spread (key = species, value = catch)

head(catch_wide)

```


# Join the Region Definitions

# Miscelaneous Functions






