---
title: "Data Visualization"
author: "Sara Pedro"
date: "February 14, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
  library(leaflet)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(DT)
```

# Reformat the data for plotting

[Alaska Department of Fish and Game, Division of Commercial Fisheries. 2017. Daily salmon escapement counts from the OceanAK database, Alaska, 1921-2017. Knowledge Network for Biocomplexity. doi:10.5063/F1S46Q6M.]

```{r}
esc <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e", method = "libcurl"), stringsAsFactors = FALSE)

head(esc)

```

* Calculate annual escapement by species and region
* Filter for just pacific salmon (Sockeye, Chinook, Coho, Pink, Chum)
* Create a data frame called annual_esc with the results from previous points

```{r}

annual_esc <- esc %>%
  separate(sampleDate, c("year", "day", "month"), sep = "-") %>% 
    # coerce year to numeric value
  mutate(year = as.numeric(year)) %>% 
  group_by(year, Species, SASAP.Region) %>% 
  summarise(count = sum(DailyCount)) %>% 
  filter(Species %in% c("Sockeye", "Chinook", "Coho", "Pink", "Chum")) 


head(annual_esc)

```


# Generate some static plots

```{r}

ggplot(annual_esc, aes(x = Species, y = count, fill = SASAP.Region)) +
  geom_col()

# or

ggplot(annual_esc) +
  geom_col(aes(x = Species, y = count), fill = "blue") # this way I can add different data with                                                         different geoms to the same plot


```


If we are using the same themes for a bunch of plots, we can save them seperately

```{r}
my_theme <- theme_test() +
  theme(legend.position = "bottom", legend.title = element_blank())
```



```{r}

ggplot(filter(annual_esc, SASAP.Region == "Kodiak"), aes(year, count, color = Species)) +
  geom_line() +
    geom_point() +
  ylab("Escapement (num of fish)") +
  xlab("Year") +
  ggtitle("Kodiak Salmon Escapement") +
  my_theme

```


# Generate 






